from turtle import *
fillcolor("red")
begin_fill()
pensize(3)
lt(50)
fd(133)
circle(50,200)
rt(140)
circle(50,200)
fd(133)
end_fill()
title("Pythontpoint")
write(" Happy Valentines Day...",align="right",font=("Times New Roman",20, "bold"))
hideturtle()
mainloop()