name=input("Enter your name: ")
city=input("Enter your city: ")
food=input("Enter your food: ")
dog=input("Enter your fav dog: ")
teacher=input("Enter your fav teacher: ")
actor=input("Enter your fav actor: ")
hobby=input("Enter your fav hobby: ")
author=input("Enter your fav author: ")
movie=input("Enter your fav movie: ")
subject=input("Enter your fav subject: ")
print("!!!INFO!!!!!")
print(name)
print(city)
print(food)
print(dog)
print(teacher)
print(actor)
print(hobby)
print(author)
print(movie)
print(subject)
print("!!!INFO!!!")
